# Generated by Django 5.0.1 on 2025-07-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_follow_follower_alter_follow_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
